### PR TITLE
Div 8000

### PR DESCRIPTION
**Pull request by ajay-beehyv**

### CODE REVIEW

**Comment by ajay-beehyv** [comment]
@samarthgr

**Comment by dileepbapat** [comment]
Does it make sense to maintain configs in separate store going forward?, one more dependency but it is worth it I guess

**Comment by ajay-beehyv** [comment]
> Does it make sense to maintain configs in separate store going forward?, one more dependency but it is worth it I guess

@dileepbapat , It's possible but Data is almost complete now for majority cases. For next major changes, config data can be added in package manager.

**Review by himeshr-egov — APPROVED** [review]

**Comment by ajay-egov** [comment]
DIV-8065 also part of this merge

**Pull request merged**
