### PR TITLE
HLM 724

### PR DESCRIPTION
**Pull request by vishwajeet-eGov**
@saiprakash-v @prasanna-egov  Please review.

### CODE REVIEW

**Review by saiprakash-v — COMMENTED** [review]
Will wait for the "Router upgrade" PR to be addressed and closed before reviewing this. There are duplicate changes

**Comment by saiprakash-v** [comment]
@vishwajeet-eGov Please remove the duplicate changes and let me know. I will review

**Comment by vishwajeet-eGov** [comment]
@saiprakash-v  Conflict resolved.

**Review by prasanna-egov — COMMENTED** [review]
For the user profile image, please get the appropriate language from Andrew.

**Review by saiprakash-v — APPROVED** [review]

**Review by prasanna-egov — APPROVED** [review]

**Pull request merged**
